# Generated by Django 5.1 on 2024-09-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="created_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата создания записи"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="Blog/image",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="updated_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата изменения записи"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Просмотров"),
        ),
    ]
