# Generated by Django 5.1 on 2024-09-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_created_at_blog_image_blog_is_published_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
    ]
