# Generated by Django 5.1 on 2024-09-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_blog_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="updated_at",
        ),
    ]
