# Generated by Django 5.1 on 2024-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_blog_created_at_remove_blog_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="created_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата создания записи"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="Blog/image",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="updated_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата изменения записи"
            ),
        ),
    ]
