# Generated by Django 5.1 on 2024-10-05 12:11

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_blog_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to=blog.utils.upload_to,
                verbose_name="Изображение",
            ),
        ),
    ]
