# Generated by Django 5.1 on 2024-10-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={
                "ordering": ["product", "version_number", "name", "version_sign"],
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
            },
        ),
    ]
