# Generated by Django 4.2.2 on 2024-10-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "create_date", "changes_date"],
                "permissions": [
                    ("can_delete_product", "can delete product"),
                    ("can_change_description", "can change description"),
                    ("can_change_category", "can change category"),
                ],
                "verbose_name": "Продукты",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
