# Generated by Django 4.2.2 on 2024-10-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "create_date", "changes_date"],
                "permissions": [
                    ("can_change_product_status", "can change product status"),
                    ("can_change_description", "can change description"),
                    ("can_change_category", "can change category"),
                ],
                "verbose_name": "Продукты",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
